# -*- coding: utf-8 -*-
"""Exercícios Python 12/04/24.ipynb

Automatically generated by Colab.
"""

print("Exercício 3a)")
i = 10
while i >= 0:
    print("Contador:", i)
    i -= 1

print("Exercício 3c)")
i = 10
acumulador = 0
while i >= 0:
    print("Contador:", i)
    acumulador += i
    i -= 1
print("Acumulador:", acumulador)

print("Exercício 4)")
i = 10
acumulador = 0
while i >= 0:
    print("Valor atual da variável i (contador):", i)
    acumulador += i
    print("Valor atual do acumulador ({} + {}): {}".format((acumulador - i), i, acumulador))
    i -= 1
